[package]
name = "configures"
version = "0.1.0"
edition = "2024"

[dependencies]
git2 = "0.20.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
thiserror = "2.0.17"
toml = "0.9.8"
whoami = "1.6.1"
